# Generated by Django 3.2.5 on 2021-07-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=50)),
            ],
        ),
    ]
