# Generated by Django 3.2.5 on 2021-07-27 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_alter_departamento_empresa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
