# Generated by Django 3.2.5 on 2021-07-27 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('departamento', '0003_delete_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('cod', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=50)),
                ('codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
        ),
    ]
