# Generated by Django 3.2.5 on 2021-07-27 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0004_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='telefono',
        ),
    ]
