# Generated by Django 3.2.5 on 2021-07-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('empresa', models.CharField(max_length=10)),
                ('departamento', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
                ('fechaIngreso', models.DateField()),
                ('curp', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
