# Generated by Django 3.2.5 on 2021-07-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_auto_20210727_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fechaIngreso',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaNacimiento',
            field=models.DateTimeField(),
        ),
    ]
