# Generated by Django 3.2.5 on 2021-08-03 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_auto_20210728_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masculino', models.CharField(max_length=50)),
                ('femenino', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sexo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='empleado.sexo'),
        ),
    ]
