# Generated by Django 3.2.5 on 2021-08-03 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_auto_20210803_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sexo',
            old_name='femenino',
            new_name='sexo',
        ),
        migrations.RemoveField(
            model_name='sexo',
            name='masculino',
        ),
    ]
